"""
sponsor_evidence_engine.py

Sprint 2: Sponsor Evidence Module engine.

Pure function — no DB, no I/O. The router owns persistence.

Given the user's sponsor situation inputs, produces:
  - warnings: issues the visa officer will likely flag
  - checklist_injections: spn_* items to merge into the VisaFile

The status of each injected item (Incomplete / Partial / Complete) is
computed on the frontend by reading file.items — it changes live as the
user marks documents, so it is never stored or returned here.
"""


# ---------------------------------------------------------------------------
# Checklist items to replace when sponsor evidence is applied.
# These are the generic items generated by the checklist engine and the
# financial-proof checker; the richer spn_* items supersede them.
# ---------------------------------------------------------------------------

SUPERSEDED_ITEM_IDS: frozenset[str] = frozenset({
    "sponsor_letter",
    "sponsor_bank_statements",
    "sponsor_relationship_proof",
    "fin_sponsor_income_proof",
})


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _item(item_id: str, title: str, category: str, priority: str,
          reason: str, guidance: str) -> dict:
    return {
        "id":       item_id,
        "title":    title,
        "category": category,
        "priority": priority,
        "reason":   reason,
        "guidance": guidance,
    }


# ---------------------------------------------------------------------------
# Engine — the only public function
# ---------------------------------------------------------------------------

def evaluate(inputs: dict) -> dict:
    """
    Evaluate a user's sponsor evidence situation and return warnings +
    checklist injections.

    inputs keys (all optional):
      relationship              str  (parent | sibling | relative | spouse |
                                      employer | other)
      sponsor_name              str  (free text, optional)
      funds_in_sponsor_account  str  (yes | no | not_sure)
      bank_statement_status     str  (ready | not_ready | not_sure)
      income_proof_available    str  (yes | no)
      income_type               str  (salary | business | savings |
                                      property_sale | other)
      large_deposits            str  (yes | no | not_sure)
      source_explainable        str  (yes | no | not_sure)

    Returns:
      {
        warnings:             list[str],
        checklist_injections: list[dict],   # spn_* items WITHOUT status
      }
    """
    relationship   = (inputs.get("relationship")             or "").lower()
    funds_ok       = (inputs.get("funds_in_sponsor_account") or "not_sure").lower()
    bank_status    = (inputs.get("bank_statement_status")    or "not_sure").lower()
    income_proof   = (inputs.get("income_proof_available")   or "no").lower()
    income_type    = (inputs.get("income_type")              or "").lower()
    large_deposits = (inputs.get("large_deposits")           or "not_sure").lower()
    explainable    = (inputs.get("source_explainable")       or "not_sure").lower()

    # ── Warnings ─────────────────────────────────────────────────────────────
    warnings: list[str] = []

    if funds_ok != "yes":
        warnings.append(
            "Funds are not confirmed to be in the sponsor's account. "
            "The money must be demonstrably available and accessible before you apply."
        )
    if bank_status != "ready":
        warnings.append(
            "Sponsor bank statement is not ready. "
            "This is a critical document — a certified bank statement must be dated "
            "within 31 days of your application."
        )
    if income_proof != "yes":
        warnings.append(
            "Sponsor income proof is not available. "
            "Visa officers need to see that the sponsor's ability to fund your studies "
            "is backed by ongoing income, not just current savings."
        )
    if large_deposits == "yes":
        warnings.append(
            "Large deposits detected in the sponsor's account. "
            "A detailed source of funds explanation with supporting evidence is required "
            "for every unusually large credit."
        )
    elif large_deposits == "not_sure":
        warnings.append(
            "Uncertain whether large deposits are present in the sponsor's account. "
            "Review the statements carefully — any unexplained large credit must be addressed."
        )
    if explainable == "no":
        warnings.append(
            "Sponsor cannot clearly explain the source of funds. "
            "This is a serious red flag. Visa officers specifically look for credible, "
            "documentable explanations of where the money came from."
        )
    elif explainable == "not_sure":
        warnings.append(
            "Sponsor source of funds explanation is unclear. "
            "Prepare written documentation now rather than waiting for a visa officer to ask."
        )

    # ── Checklist injections (spn_*) ─────────────────────────────────────────
    injections: list[dict] = []

    # Core documents — required for every sponsored application.
    injections.append(_item(
        "spn_consent_letter",
        "Sponsor consent letter / affidavit of support",
        "sponsor", "critical",
        "The visa officer needs the sponsor's written commitment to fund your studies.",
        "The letter must be signed and ideally notarised. It should name you, state the "
        "sponsor's relationship to you, confirm they will cover tuition and living costs "
        "for the full duration, and be dated within 6 months of your application.",
    ))
    injections.append(_item(
        "spn_relationship_proof",
        "Proof of sponsor relationship",
        "sponsor", "critical",
        "The officer must be able to verify the sponsor's legal relationship to you.",
        "Provide a birth certificate (parent/sibling), marriage certificate (spouse), or "
        "family registration document. For employer sponsors, an employment contract or "
        "official company letter is required.",
    ))
    injections.append(_item(
        "spn_bank_statement",
        "Sponsor bank statement",
        "sponsor", "critical",
        "The sponsor's bank statement is the primary financial evidence for the visa.",
        "Provide official statements covering at least the last 3–6 months. The closing "
        "balance must meet the country's financial threshold. The statement must be bank-stamped "
        "or digitally certified and dated within 31 days of your application.",
    ))
    injections.append(_item(
        "spn_id_document",
        "Sponsor ID / passport / CNIC",
        "sponsor", "critical",
        "The sponsor's identity must be verifiable by the visa officer.",
        "Include a clear copy of the sponsor's passport, national ID (CNIC), or equivalent "
        "government-issued photo ID. Ensure the document is valid and not expired.",
    ))
    injections.append(_item(
        "spn_income_proof",
        "Sponsor income proof",
        "sponsor", "critical",
        "The officer must verify the sponsor has ongoing income sufficient to fund your studies.",
        "Collect the last 3–6 months of salary slips, a bank salary credit history, or "
        "certified business accounts / tax returns for self-employed sponsors. An employer "
        "letter confirming salary and position adds further weight.",
    ))

    # Conditional — income type specific.
    if income_type == "salary":
        injections.append(_item(
            "spn_salary_slips",
            "Salary slips / employment letter",
            "sponsor", "high",
            "Salary evidence is the most straightforward proof of a sponsor's ability to fund.",
            "Collect the last 3–6 months of salary slips. An employer letter confirming "
            "the sponsor's role, salary, and employment duration strengthens the package.",
        ))

    if income_type == "business":
        injections.append(_item(
            "spn_business_documents",
            "Business registration / ownership documents / accounts",
            "sponsor", "high",
            "Self-employed sponsors must prove both the legitimacy and profitability of "
            "their business.",
            "Provide business registration documents, certified financial accounts for the "
            "last 2 years, and a business bank statement. A letter from a chartered accountant "
            "or tax return further validates the income.",
        ))

    # Conditional — large deposits or unclear income source.
    needs_source_letter = (
        large_deposits in ("yes", "not_sure")
        or explainable in ("no", "not_sure")
        or income_type in ("property_sale", "other", "")
    )
    if needs_source_letter:
        injections.append(_item(
            "spn_source_of_funds_letter",
            "Source of funds explanation letter",
            "sponsor", "critical",
            "Any large or unusual credit in the sponsor's account must be explained in writing.",
            "The sponsor should write a signed statement explaining the origin of each "
            "significant deposit, referencing dates and amounts. This must be consistent "
            "with supporting evidence provided.",
        ))

    if large_deposits == "yes":
        injections.append(_item(
            "spn_large_deposit_explanation",
            "Supporting evidence for large deposits",
            "sponsor", "critical",
            "Unexplained large credits are a common refusal reason — documentary proof is "
            "non-negotiable.",
            "Provide the underlying document for each large deposit: property sale deed, "
            "employer bonus letter, inheritance documents, investment redemption certificate, "
            "or similar. Match each document to the corresponding bank credit entry.",
        ))

    # Always recommended.
    injections.append(_item(
        "spn_tax_returns",
        "Sponsor tax returns (recommended)",
        "sponsor", "standard",
        "Tax returns provide an independent, government-verified view of the sponsor's income.",
        "Include the last 1–2 years of filed tax returns. Even if not strictly required, "
        "they significantly strengthen the financial evidence package.",
    ))

    return {
        "warnings":             warnings,
        "checklist_injections": injections,
    }
