from sqlalchemy import (
    Boolean, Column, String, DateTime, Integer, Float, JSON, ForeignKey, Text,
    UniqueConstraint, Enum as SAEnum,
)
from sqlalchemy.dialects.postgresql import UUID
from datetime import datetime, timezone
import uuid

from database import Base


def utc_now_naive() -> datetime:
    """UTC timestamp matching PostgreSQL TIMESTAMP WITHOUT TIME ZONE columns."""
    return datetime.now(timezone.utc).replace(tzinfo=None)


class User(Base):
    __tablename__ = "users"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    auth_user_id = Column(String, unique=True, nullable=True, index=True)
    email = Column(String, unique=True, nullable=True, index=True)
    # Billing plan for entitlements/quotas. "free" by default; a paywall can set
    # this to a paid tier later without any schema change. See services/entitlements.py.
    plan = Column(String, nullable=False, default="free", server_default="free")
    created_at = Column(DateTime, default=utc_now_naive, nullable=False)


class VisaCheck(Base):
    __tablename__ = "visa_checks"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    country              = Column(String,  nullable=False)
    visa_type            = Column(String,  nullable=False)
    score                = Column(Integer, nullable=False)
    result               = Column(String,  nullable=False)
    result_description   = Column(String,  nullable=True)

    # Phase 1 fields — original schema
    critical_blockers    = Column(JSON,    nullable=False, default=list)
    warnings             = Column(JSON,    nullable=False, default=list)
    recommendations      = Column(JSON,    nullable=False, default=list)

    # Phase 4B fields — added by migration 002_add_result_fields
    # nullable=True so existing rows (NULL) are safe; app defaults to [] / {}
    high_risk_flags      = Column(JSON,    nullable=True)
    soft_warnings        = Column(JSON,    nullable=True)
    normalized_answers   = Column(JSON,    nullable=True)
    sources_used         = Column(JSON,    nullable=True)

    created_at           = Column(DateTime, default=utc_now_naive, nullable=False)


class UserVisaProfile(Base):
    __tablename__ = "user_visa_profiles"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
        index=True,
    )

    preferred_name          = Column(String,  nullable=True)
    applying_from_country   = Column(String,  nullable=True)
    nationality             = Column(String,  nullable=True)
    applicant_type          = Column(String,  nullable=True)
    interested_countries    = Column(JSON,    nullable=True)   # list[str]
    primary_country         = Column(String,  nullable=True)
    study_level             = Column(String,  nullable=True)
    intended_intake         = Column(String,  nullable=True)
    admission_status        = Column(String,  nullable=True)
    funding_source          = Column(String,  nullable=True)
    sponsor_relationship    = Column(String,  nullable=True)
    funds_arranged          = Column(String,  nullable=True)
    bank_statement_status   = Column(String,  nullable=True)
    previous_refusal        = Column(String,  nullable=True)
    study_gap               = Column(String,  nullable=True)
    dependants              = Column(String,  nullable=True)
    main_help_needed        = Column(JSON,    nullable=True)   # list[str]
    onboarding_completed    = Column(Boolean, nullable=False,  default=False)

    created_at              = Column(DateTime, default=utc_now_naive, nullable=False)
    updated_at              = Column(DateTime, default=utc_now_naive, nullable=False)


class VisaFile(Base):
    """
    A working visa document file for a user, generated by the checklist engine
    from their profile + a specific readiness check.

    One file per (user, visa_check) pair — see visa_file_service.fetch_or_create.
    `items` is the full checklist (list of item dicts); category progress and
    completion stats are derived from it at serialization time, never stored.
    """
    __tablename__ = "visa_files"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    # The readiness check this file was built from. SET NULL so deleting a check
    # leaves the file intact (its checklist is still useful).
    visa_check_id = Column(
        UUID(as_uuid=True),
        ForeignKey("visa_checks.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    country    = Column(String, nullable=False)
    visa_type  = Column(String, nullable=False, default="student_visa")

    # Full checklist: list of item dicts
    #   {id, title, category, priority, status, reason, guidance}
    items           = Column(JSON, nullable=False, default=list)

    # Persisted Financial Proof Checker evaluation: {inputs: {...}, result: {...}}
    # NULL for files created before Sprint 2.
    financial_proof  = Column(JSON, nullable=True)

    # Persisted Sponsor Evidence Module evaluation: {inputs: {...}, warnings: [...]}
    # NULL for files created before Sprint 2 or when not sponsor-funded.
    sponsor_evidence = Column(JSON, nullable=True)

    created_at = Column(DateTime, default=utc_now_naive, nullable=False)
    updated_at = Column(DateTime, default=utc_now_naive, nullable=False)


class VisaTimeline(Base):
    """
    A backward deadline plan for a user's visa journey (Module C).

    One timeline per user (unique on user_id) — regenerated when the user
    changes their intake date or destination. `milestones` is the full list of
    milestone dicts; the user can edit each milestone's status/note.
    """
    __tablename__ = "visa_timelines"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
        index=True,
    )

    country     = Column(String, nullable=False)
    # Course intake date, stored as an ISO "YYYY-MM-DD" string (JSON-friendly).
    intake_date = Column(String, nullable=False)

    # Full milestone list: [{id, label, due_date, status, note, source}]
    milestones  = Column(JSON, nullable=False, default=list)

    created_at = Column(DateTime, default=utc_now_naive, nullable=False)
    updated_at = Column(DateTime, default=utc_now_naive, nullable=False)


class SopReview(Base):
    """
    A stored Statement-of-Purpose review (Module E).

    For privacy we store only a hash + character count of the submitted text,
    never the SOP itself. `feedback` holds the normalized AI assessment. Rows
    also serve as the daily usage log for entitlements/quotas.
    """
    __tablename__ = "sop_reviews"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    country     = Column(String,  nullable=True)
    input_chars = Column(Integer, nullable=False, default=0)
    input_hash  = Column(String,  nullable=True)     # sha256 of the SOP text
    feedback    = Column(JSON,    nullable=False, default=dict)

    created_at  = Column(DateTime, default=utc_now_naive, nullable=False, index=True)


class InterviewSession(Base):
    """
    A mock credibility-interview session (Module F).

    `transcript` is the full Q/A list ([{role, content}]); `assessment` is the
    final structured evaluation (NULL until the session is finished). Rows also
    serve as the daily usage log for entitlements/quotas.
    """
    __tablename__ = "interview_sessions"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    country    = Column(String, nullable=True)
    status     = Column(String, nullable=False, default="active")   # active | completed
    transcript = Column(JSON,   nullable=False, default=list)        # [{role, content}]
    assessment = Column(JSON,   nullable=True)                       # set on finish

    created_at = Column(DateTime, default=utc_now_naive, nullable=False, index=True)
    updated_at = Column(DateTime, default=utc_now_naive, nullable=False)


# ---------------------------------------------------------------------------
# Document Guidance Module
# ---------------------------------------------------------------------------
# A personalized document dependency graph: which documents a user needs, in what
# order, from which official source. documents/offices use human-readable string
# slug PKs so the hand-verified seed file and edges stay easy to author + edit.

# Stored user progress values (the engine additionally computes 'blocked'/'ready').
USER_DOCUMENT_STATUS_VALUES = ("have", "blocked", "in_progress", "done")


class DocumentRef(Base):
    """A single document a user must obtain, with its official source + costs."""
    __tablename__ = "documents"

    id                = Column(String, primary_key=True)               # slug, e.g. "cnic"
    name              = Column(String, nullable=False)
    country_relevance = Column(JSON,   nullable=False, default=list)   # list[str] target countries
    issuing_authority = Column(String, nullable=True)
    official_url      = Column(String, nullable=True)                  # canonical process source
    normal_cost       = Column(Integer, nullable=True)                 # nullable — prefer linking
    urgent_cost       = Column(Integer, nullable=True)
    normal_days       = Column(Integer, nullable=True)
    urgent_days       = Column(Integer, nullable=True)
    validity_months   = Column(Integer, nullable=True)                 # for expiring docs
    office_id         = Column(String, ForeignKey("offices.id", ondelete="SET NULL"), nullable=True)
    display_order     = Column(Integer, nullable=False, default=0)     # topo tie-break
    last_verified_at  = Column(DateTime, nullable=False)               # REQUIRED, shown in UI
    source_url        = Column(String, nullable=True)                  # where last_verified_at confirmed


class DocumentEdge(Base):
    """A prerequisite edge: `document_id` requires `requires_id` (optionally if `condition`)."""
    __tablename__ = "document_edges"

    id          = Column(Integer, primary_key=True, autoincrement=True)
    document_id = Column(String, ForeignKey("documents.id", ondelete="CASCADE"), nullable=False, index=True)
    requires_id = Column(String, ForeignKey("documents.id", ondelete="CASCADE"), nullable=False, index=True)
    condition   = Column(String, nullable=True)   # e.g. "needs_intermediate_equivalence"


class Office(Base):
    """A physical office. The map link is generated from lat/lng, never stored."""
    __tablename__ = "offices"

    id                     = Column(String, primary_key=True)          # slug
    authority              = Column(String, nullable=False)
    city                   = Column(String, nullable=True)
    address                = Column(String, nullable=True)
    lat                    = Column(Float,  nullable=True)
    lng                    = Column(Float,  nullable=True)
    hours                  = Column(String, nullable=True)
    online_appointment_url = Column(String, nullable=True)             # legal fast-track entry
    last_verified_at       = Column(DateTime, nullable=False)          # REQUIRED


class UserDocumentState(Base):
    """Per-user progress on a document. Future-readable by the scoring engine."""
    __tablename__ = "user_document_state"
    __table_args__ = (UniqueConstraint("user_id", "document_id", name="uq_user_document"),)

    id          = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id     = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    document_id = Column(String, ForeignKey("documents.id", ondelete="CASCADE"), nullable=False, index=True)
    status      = Column(SAEnum(*USER_DOCUMENT_STATUS_VALUES, name="user_document_status"), nullable=False)
    updated_at  = Column(DateTime, default=utc_now_naive, nullable=False)


class UserDocument(Base):
    """
    A bank statement the user uploaded to the Financial Document Checker.

    Privacy: the raw file is processed in memory and NEVER persisted. We store
    only the derived fields (`extracted`), the rule-engine result (`result`), and
    a sha256 of the original bytes (`content_hash`) for dedupe/audit — mirroring
    the SopReview hash-only approach. `extracted` holds applicant PII (balances,
    account holder, bank name) and is encrypted at the application layer before
    write via services/encryption.py (see the column note below).

    Lifecycle: a row is created at upload (status "parsed", result NULL); the
    evaluate step overwrites `extracted` with the user-confirmed values and fills
    `result` (status "evaluated"). Rows also serve as the daily usage log for
    entitlements/quotas (see services/entitlements.py).
    """
    __tablename__ = "user_documents"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    doc_type     = Column(String,  nullable=False, default="financial_statement")
    country      = Column(String,  nullable=True)
    bank_id      = Column(String,  nullable=True)        # detected bank slug, or NULL (generic)
    status       = Column(String,  nullable=False, default="parsed")  # parsed | evaluated
    content_hash = Column(String,  nullable=True)        # sha256 of the uploaded bytes

    # Parsed-then-confirmed statement (ParsedStatement.to_dict shape).
    # Encrypted at rest: stored as the Fernet envelope produced by
    # services.encryption.encrypt_json; read back via decrypt_json. PII — never
    # store this column as plaintext.
    extracted    = Column(JSON,    nullable=True)
    # financial_document_engine.evaluate(...) output. NULL until evaluated.
    result       = Column(JSON,    nullable=True)

    created_at   = Column(DateTime, default=utc_now_naive, nullable=False, index=True)
    updated_at   = Column(DateTime, default=utc_now_naive, nullable=False)


class VisaOutcome(Base):
    """
    A self-reported visa decision (Module 3: the outcome loop).

    Closes the loop from "here's your readiness score" to "here's what actually
    happened", which (a) lets us prove efficacy via approval-rate-by-score and
    (b) calibrates the engine. `score` is snapshotted from the linked check at
    report time so analytics survive deletion of the check.
    """
    __tablename__ = "visa_outcomes"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    # The readiness check this outcome relates to. SET NULL keeps the outcome (and
    # its snapshotted score) for analytics even if the check is later deleted.
    visa_check_id = Column(
        UUID(as_uuid=True),
        ForeignKey("visa_checks.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    country         = Column(String,  nullable=True)
    score           = Column(Integer, nullable=True)   # snapshot of the check's score
    outcome         = Column(String,  nullable=False)  # approved | refused | withdrawn | pending
    refusal_reasons = Column(JSON,    nullable=True)    # list[str], when refused
    decided_at      = Column(String,  nullable=True)    # ISO "YYYY-MM-DD" of the decision

    created_at      = Column(DateTime, default=utc_now_naive, nullable=False, index=True)
    updated_at      = Column(DateTime, default=utc_now_naive, nullable=False)


class UserTrustState(Base):
    """
    Per-user state for the Trust/Freshness module (Module 2).

    Tracks the most recent changelog date the user has acknowledged, so we can
    surface "what changed since you last checked" as an in-app alert, plus an
    opt-in flag for emailed rule-change alerts. One row per user.
    """
    __tablename__ = "user_trust_state"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
        index=True,
    )

    # ISO "YYYY-MM-DD" of the newest changelog entry the user has seen, per country.
    # Shape: {"uk": "2024-01-02", ...}. JSON keeps it flexible across countries.
    last_seen_change = Column(JSON, nullable=False, default=dict)
    alerts_opt_in    = Column(Boolean, nullable=False, default=False)

    created_at = Column(DateTime, default=utc_now_naive, nullable=False)
    updated_at = Column(DateTime, default=utc_now_naive, nullable=False)


class Organization(Base):
    """
    A consultant/agency workspace (Module 5: B2B). The creator becomes the owner
    via an OrgMembership. Students are linked as ManagedClient rows (with consent).
    """
    __tablename__ = "organizations"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    name           = Column(String, nullable=False)
    plan           = Column(String, nullable=False, default="team", server_default="team")
    owner_user_id  = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    created_at     = Column(DateTime, default=utc_now_naive, nullable=False)


class OrgMembership(Base):
    """A staff member (consultant/admin/owner) of an organization."""
    __tablename__ = "org_memberships"
    __table_args__ = (UniqueConstraint("org_id", "user_id", name="uq_org_member"),)

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    org_id  = Column(UUID(as_uuid=True), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    role    = Column(String, nullable=False, default="consultant")   # owner | consultant | admin

    created_at = Column(DateTime, default=utc_now_naive, nullable=False)


class ManagedClient(Base):
    """
    A student managed by an organization. Invited by email; only after the client
    *accepts* (status "active") may the consultant view their journey — consent is
    required by design. `client_user_id` is filled once the client is resolved.
    """
    __tablename__ = "managed_clients"
    __table_args__ = (UniqueConstraint("org_id", "client_email", name="uq_org_client_email"),)

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    org_id          = Column(UUID(as_uuid=True), ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True)
    client_email    = Column(String, nullable=False, index=True)
    client_user_id  = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True)
    status          = Column(String, nullable=False, default="invited")  # invited | active | declined | removed
    invited_by_user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True)

    created_at = Column(DateTime, default=utc_now_naive, nullable=False)
    updated_at = Column(DateTime, default=utc_now_naive, nullable=False)


class Report(Base):
    """
    A generated, downloadable Readiness Report (engine → Gemini narration → PDF).

    Persistence + determinism (constraint #4): a report is built and narrated ONCE
    at assessment time, then cached. `cache_key` = sha256(structured_engine_output
    + template_version + prompt_version); a rebuild with the same inputs finds this
    row and returns byte-identical data — the download path makes ZERO LLM calls.

    Access (constraint #7): `token` is an unguessable secret (secrets.token_urlsafe)
    and is the ONLY handle used in URLs — separate from the human-readable
    `report_id`, so report ids are never enumerable.

    PII (constraint #8): `data_encrypted` is the FULL ReportData payload (which
    includes the applicant's name and personal fields) stored as the Fernet
    envelope from services.encryption.encrypt_json — never plaintext at rest.
    """
    __tablename__ = "reports"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    # The readiness check this report was built from. SET NULL keeps the (already
    # rendered) report usable even if the underlying check is later deleted.
    visa_check_id = Column(
        UUID(as_uuid=True),
        ForeignKey("visa_checks.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    # Human-readable id shown IN the report (e.g. "PV-CA-2026-0417"). NOT a URL key.
    report_id = Column(String, nullable=False, unique=True, index=True)
    # Unguessable access token — the only id that appears in URLs.
    token = Column(String, nullable=False, unique=True, index=True)

    # sha256(engine_output + template_version + prompt_version) — the cache key.
    cache_key        = Column(String, nullable=False, index=True)
    template_version = Column(String, nullable=False)
    prompt_version   = Column(String, nullable=False)
    # True when Gemini narration succeeded; False when deterministic fallback prose
    # was used (constraint #5). Observability only — the report is valid either way.
    narrated_by_ai   = Column(Boolean, nullable=False, default=False)

    # The full ReportData payload, Fernet-encrypted (see services.encryption). PII —
    # never store as plaintext.
    data_encrypted   = Column(JSON, nullable=False)

    created_at = Column(DateTime, default=utc_now_naive, nullable=False, index=True)


class Correction(Base):
    """A user-submitted "this is wrong / office moved" flag. No moderation UI in MVP."""
    __tablename__ = "corrections"

    id          = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id     = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    document_id = Column(String, ForeignKey("documents.id", ondelete="SET NULL"), nullable=True)
    office_id   = Column(String, ForeignKey("offices.id", ondelete="SET NULL"), nullable=True)
    note        = Column(Text,   nullable=False)
    created_at  = Column(DateTime, default=utc_now_naive, nullable=False, index=True)
